version: "3.8"

services:
  ansible_host:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./ansible:/ansible
    tty: true
    stdin_open: true

