---
- hosts: "all"
  tasks:
  - name: Clone repo to workdir/
    git:
      repo: https://github.com/PETEPEtrek/sberPDRISexampleProject.git
      dest: workdir/

  - name: Copy Dockerfile to workdir/
    copy:
      src: ./Dockerfile
      dest: workdir/Dockerfile
      owner: petepetrek
      group: petepetrek
      mode: '0644'

  - name: Build image
    docker_image:
      name: sber_pdris_project
      build:
        path: workdir/
      source: build
      state: present

  - name: Start container with a command
    docker_container:
      name: sber_pdris_project
      image: sber_pdris_project
      command: ["go", "run", "main.go"]
